version: '3.9'

services:


  mydjangoserver:
    build: backend
    container_name: mydjangoserver

    command: python3 manage.py runserver 172.19.0.2:8000

    volumes:
      - .:/backend


    ports:
      - "8000:8000"

  myreact:
    build: frontend
    container_name: myreact

    command: npm run dev

    volumes:
      - .:/frontend


    ports:
      - "5173:5173"

    depends_on:
      - mydjangoserver