# Generated by Django 5.0.3 on 2024-11-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='affiliate',
        ),
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
    ]
