# Generated by Django 5.0.3 on 2024-11-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
