# Generated by Django 5.0.3 on 2024-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_comment_affiliate_order_text_delete_affiliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена заказа'),
        ),
    ]
