# Generated by Django 5.0.3 on 2024-11-04 11:33

import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ингридиент')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.BooleanField(default=False, verbose_name='Основная категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='nested_categories',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='core.category', verbose_name='Дочерние категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='core.ingredient', verbose_name='Ингридиенты'),
        ),
    ]
